services:
  # MongoDB Database
  mongo:
    image: mongo:6.0
    container_name: notification_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=notification-system

volumes:
  mongo_data:
